# Generated by Django 3.2 on 2021-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerwebsite', '0003_auto_20210507_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic')], default='EN', max_length=30),
        ),
    ]
