# Generated by Django 3.2 on 2021-05-13 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancerwebsite', '0005_auto_20210514_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
