# Generated by Django 3.2 on 2021-05-13 22:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerwebsite', '0006_alter_job_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], default='Hello', max_length=49),
        ),
    ]
