# Generated by Django 3.2 on 2021-05-14 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerwebsite', '0009_auto_20210514_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelance',
            name='user',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='freelance',
        ),
    ]
