# Generated by Django 3.2 on 2021-05-14 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerwebsite', '0010_auto_20210514_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
