# Generated by Django 3.2 on 2021-05-15 16:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerwebsite', '0011_reviews_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Programming'), ('item_key2', 'Graphic Design'), ('item_key3', 'General'), ('item_key4', 'Hardware'), ('item_key5', 'Django')], default='General', max_length=49),
        ),
    ]
