# Generated by Django 3.2 on 2021-05-15 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerwebsite', '0012_alter_job_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='finished_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
